---
title: "Who We Serve"
output:
  beamer_presentation: default
  ioslides_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(googlesheets4)
library(patchwork)
library(hrbrthemes)
library(janitor)
library(forcats)

extrafont::loadfonts()

if(!sheets_has_token()){
  sheets_auth(email = 'schneeman@gmail.com')
}

id <- NULL
if(sheets_has_token()) {
  sheet <- sheets_find(pattern = '2019 Fall Annual Survey Data_Breakdown by Scale')
  id <- sheet$id
}

survey <- sheets_get(id)

survey_df <- sheets_read(id, sheet=survey$sheet$name[1], skip = 2) %>% clean_names()

base_color <- "#4D7637"

```

```{r make-charts, warning=FALSE}
explorer_gender <- survey_df %>% 
  group_by(gender) %>% summarize(ct = n()) %>%
  ggplot(aes(x=gender, y=ct, fill=gender)) +
  geom_col(fill=base_color) + theme_ipsum() +
  scale_fill_ipsum() + theme(legend.position = "none")

grades <- survey_df %>% group_by(grade) %>% summarize(ct = n()) %>%
  ggplot(aes(x=grade, y=ct)) +
  geom_col(fill=base_color) + theme_ipsum() +
  theme(legend.position = "none") + labs(
    title = "Grade Level"
  )

lunch <- survey_df %>% mutate(do_you_receive_free_reduced_lunch = if_else(do_you_receive_free_reduced_lunch %in% c('Yes', 'No'), do_you_receive_free_reduced_lunch, "I don't know")) %>%
  group_by(do_you_receive_free_reduced_lunch) %>% summarize(ct = n()) %>%
  ggplot(aes(x=do_you_receive_free_reduced_lunch, y=ct)) +
  geom_col(fill=base_color) + theme_ipsum() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(
    title = "Free Lunch"
  )

last_gpa <- function(gpa_string) {
  parsed <- str_split(gpa_string, "\\|", simplify = TRUE)
  parsed[length(parsed)] %>% str_trim()
}

# gpa should be ordered descending. This is a bit difficult b/c the GPA values are pretty diverse and
# not exactly predictable in general. But since this is a static survey, we can hard code for
# now

gpa_levels <- c("A/A+", "A-", "B+", "B", "B-",  "C+", "C" , "C-", "D or lower", "Not Sure" )

# we will replace the "No Clue" and "NA" with "Not Sure" down below

# gotta use rowwise here to apply the function correctly
gpa <- survey_df %>% rowwise() %>%
  mutate(last_gpa = last_gpa(overall_grade_point_average_gpa_in_school),
         last_gpa = if_else(last_gpa %in% gpa_levels, last_gpa, "Not Sure"),
         last_gpa = factor(last_gpa, levels = gpa_levels)) %>% 
  group_by(last_gpa) %>% summarize(ct = n()) %>%
    ggplot(aes(x=last_gpa, y=ct)) +
  geom_col(fill=base_color) + theme_ipsum() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(
    title = "Most Recent GPA",
    x = "GPA"
  )

# need to order the absences

absence_levels <- c("0", "1", "2", "2 or 3", "3", "4", "5", "6", "7", "8", "9", "10", "Unknown")

absences <- survey_df %>% mutate(how_many_absences_have_you_had_in_the_last_2_weeks_of_school = as.character(how_many_absences_have_you_had_in_the_last_2_weeks_of_school)) %>%
  mutate(how_many_absences_have_you_had_in_the_last_2_weeks_of_school = if_else(how_many_absences_have_you_had_in_the_last_2_weeks_of_school == "None", "0", how_many_absences_have_you_had_in_the_last_2_weeks_of_school),
         how_many_absences_have_you_had_in_the_last_2_weeks_of_school = if_else(how_many_absences_have_you_had_in_the_last_2_weeks_of_school == "NULL", "Unknown", how_many_absences_have_you_had_in_the_last_2_weeks_of_school)) %>%
  mutate(how_many_absences_have_you_had_in_the_last_2_weeks_of_school = factor(how_many_absences_have_you_had_in_the_last_2_weeks_of_school, levels = absence_levels)) %>%
  group_by(how_many_absences_have_you_had_in_the_last_2_weeks_of_school) %>%
  summarize(ct = n()) %>%
  ggplot(aes(x=how_many_absences_have_you_had_in_the_last_2_weeks_of_school, y=ct)) +
  geom_col(fill=base_color) + theme_ipsum() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(
    title = "Two-Week Absence Count",
    x = "Absences"
  )

extracurriculars <- survey_df %>% mutate(how_many_extracurriculars_do_you_participate_in_at_school = as.character(how_many_extracurriculars_do_you_participate_in_at_school),
                                         how_many_extracurriculars_do_you_participate_in_at_school = if_else(how_many_extracurriculars_do_you_participate_in_at_school == "4", "4 or more", how_many_extracurriculars_do_you_participate_in_at_school)) %>%
  filter(how_many_extracurriculars_do_you_participate_in_at_school != "NULL") %>%
  group_by(how_many_extracurriculars_do_you_participate_in_at_school) %>%
  summarize(ct = n()) %>%
  ggplot(aes(x=how_many_extracurriculars_do_you_participate_in_at_school, y=ct)) +
  geom_col(fill=base_color) + theme_ipsum() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(
    title = "Number of\nExtracurricular Activities",
    x = "Extracurriculars"
  )


# home residents
resident_levels <- rep(1:6) %>% as.character
resident_levels <- c(resident_levels, "7 or more", "I don't know")

residents <- survey_df %>% 
  mutate(how_many_people_live_in_your_house = na_if(how_many_people_live_in_your_house, c("IDK"))) %>%
  mutate(how_many_people_live_in_your_house = na_if(how_many_people_live_in_your_house, c("NULL"))) %>% 
  mutate(how_many_people_live_in_your_house = as.character(how_many_people_live_in_your_house)) %>%
  mutate(how_many_people_live_in_your_house = if_else(how_many_people_live_in_your_house %in% resident_levels, how_many_people_live_in_your_house, "7 or more")) %>%
  mutate(how_many_people_live_in_your_house = as.character(how_many_people_live_in_your_house)) %>%
    mutate(how_many_people_live_in_your_house = if_else(is.na(how_many_people_live_in_your_house), "I don't know", how_many_people_live_in_your_house)) %>%
  mutate(how_many_people_live_in_your_house = factor(how_many_people_live_in_your_house, levels = resident_levels)) %>%
  group_by(how_many_people_live_in_your_house) %>%
  summarize(ct = n()) %>%
    ggplot(aes(x=how_many_people_live_in_your_house, y=ct)) +
  geom_col(fill=base_color) + theme_ipsum() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(
    title = "Household Residents",
    x = "Residents"
  )


# Languages

languages <- survey_df %>%
  group_by(what_language_is_spoken_at_home_circle_all_that_apply_separate_languages_with_a_vertical_bar_e_g) %>% 
  summarise(ct = n()) %>%
  mutate(what_language_is_spoken_at_home_circle_all_that_apply_separate_languages_with_a_vertical_bar_e_g = fct_reorder(what_language_is_spoken_at_home_circle_all_that_apply_separate_languages_with_a_vertical_bar_e_g, ct, .desc = TRUE)) %>% 
  ggplot(aes(x=what_language_is_spoken_at_home_circle_all_that_apply_separate_languages_with_a_vertical_bar_e_g, y=ct)) +
  geom_col(fill=base_color) + theme_ipsum() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(
    title = "Household Languages",
    x = "Languages"
  )

# siblings

sib_levels <- 0:7 %>% as.character()

siblings <- survey_df %>%
  mutate(how_many_siblings_do_you_have = as.character(how_many_siblings_do_you_have),
         how_many_siblings_do_you_have = if_else(how_many_siblings_do_you_have == "None", "0", how_many_siblings_do_you_have)) %>%
  group_by(how_many_siblings_do_you_have) %>% 
  summarise(ct = n()) %>%
  mutate(how_many_siblings_do_you_have = factor(how_many_siblings_do_you_have, levels = sib_levels)) %>% 
  ggplot(aes(x=how_many_siblings_do_you_have, y=ct)) +
  geom_col(fill=base_color) + theme_ipsum() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(
    title = "Number of Siblings",
    x = "Siblings"
  )

#siblings over 20

siblings_over_twenty <- survey_df %>% filter(how_many_siblings_do_you_have != "None") %>%
  mutate(how_many_of_your_siblings_are_over_the_age_of_20 = as.character(how_many_of_your_siblings_are_over_the_age_of_20),
         how_many_of_your_siblings_are_over_the_age_of_20 = if_else(how_many_of_your_siblings_are_over_the_age_of_20 == "None", "0", how_many_of_your_siblings_are_over_the_age_of_20)) %>%
  group_by(how_many_of_your_siblings_are_over_the_age_of_20) %>% 
  summarise(ct = n()) %>%
  mutate(how_many_of_your_siblings_are_over_the_age_of_20 = factor(how_many_of_your_siblings_are_over_the_age_of_20, levels = sib_levels)) %>% 
  ggplot(aes(x=how_many_of_your_siblings_are_over_the_age_of_20, y=ct)) +
  geom_col(fill=base_color) + theme_ipsum() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(
    title = "Number of Siblings\nOver 20",
    x = "Siblings"
  )

# siblings attending/attended college

siblings_college <- survey_df %>% filter(how_many_siblings_do_you_have != "None") %>%
  mutate(how_many_of_your_siblings_attend_college_or_are_college_graduates = as.character(how_many_of_your_siblings_attend_college_or_are_college_graduates),
         how_many_of_your_siblings_attend_college_or_are_college_graduates = if_else(how_many_of_your_siblings_attend_college_or_are_college_graduates == "None", "0", how_many_of_your_siblings_attend_college_or_are_college_graduates)) %>%
  group_by(how_many_of_your_siblings_attend_college_or_are_college_graduates) %>% 
  summarise(ct = n()) %>%
  mutate(how_many_of_your_siblings_attend_college_or_are_college_graduates = factor(how_many_of_your_siblings_attend_college_or_are_college_graduates, levels = sib_levels)) %>% 
  ggplot(aes(x=how_many_of_your_siblings_attend_college_or_are_college_graduates, y=ct)) +
  geom_col(fill=base_color) + theme_ipsum() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(
    title = "Number of Siblings\nAttending/Attended College",
    x = "Siblings"
  )

# parental education

last_edu <- function(edu_string) {
  parsed <- str_split(edu_string, "\\|", simplify = TRUE)
  parsed[length(parsed)] %>% str_trim()
}

replace_values <- function(edu_string) {
  edu_string = na_if(edu_string, "NA")
  edu_string = na_if(edu_string, "N/A")
  edu_string = if_else(edu_string == "Education after high school other than 2-year or 4-year (e.g. trade school)", "Completed trade/technical school", edu_string)
  edu_string = if_else(edu_string == "Some college (community/junior college or more 4-years college study)", "Some university/college", edu_string)
  edu_string = if_else(edu_string == "Some college (community/junior college or some 4-year college study)", "Some university/college", edu_string) 
  edu_string = if_else(edu_string == "Less than high schoo", "Less than high school", edu_string)
  edu_string = if_else(edu_string == "Completed high school","High school graduate (or G.E.D)",   edu_string)
  edu_string = if_else(edu_string == "High school graduage (or G.E.D)", "High school graduate (or G.E.D)", edu_string)
  edu_string = if_else(edu_string == "Completed univsersity/college", "Completed university/college", edu_string)
  edu_string
}

father_edu_plot <- survey_df %>%  
  rowwise() %>%
  mutate(father_edu = last_edu(what_is_the_highest_level_of_education_of_your_parents_father),
         father_edu = replace_values(father_edu),
         father_edu = as.character(father_edu)) %>% 
  group_by(father_edu) %>% 
  summarise(ct = n()) %>%
  mutate(father_edu = fct_reorder(father_edu, ct, .desc=TRUE)) %>% 
  ggplot(aes(x=father_edu, y=ct)) +
  geom_col(fill=base_color) + theme_ipsum() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(
    title = "Father's Education Level",
    x = "Education"
  )

mother_edu_plot <- survey_df %>%  
  rowwise() %>%
  mutate(mother_edu = last_edu(what_is_the_highest_level_of_education_of_your_parents_mother),
         mother_edu = replace_values(mother_edu),
         mother_edu = as.character(mother_edu)) %>% 
  group_by(mother_edu) %>% 
  summarise(ct = n()) %>% 
  mutate(mother_edu = fct_reorder(mother_edu, ct, .desc=TRUE)) %>% 
  ggplot(aes(x=mother_edu, y=ct)) +
  geom_col(fill=base_color) + theme_ipsum() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(
    title = "Mother's Education Level",
    x = "Education"
  )


post_high_school <- survey_df %>%
    group_by(what_do_you_plan_to_do_after_high_school_separate_multiple_responses_with_a_vertical_bar_e_g) %>% 
  summarise(ct = n()) %>% 
  mutate(what_do_you_plan_to_do_after_high_school_separate_multiple_responses_with_a_vertical_bar_e_g = fct_reorder(what_do_you_plan_to_do_after_high_school_separate_multiple_responses_with_a_vertical_bar_e_g, ct, .desc=FALSE)) %>% 
  ggplot(aes(x=what_do_you_plan_to_do_after_high_school_separate_multiple_responses_with_a_vertical_bar_e_g, y=ct)) +
  geom_col(fill=base_color) + theme_ipsum() +
  coord_flip() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = -45, hjust = 1)) + 
  labs(
    title = "Post High School",
    x = "Plan"
  )

```

## Explore Austin 2019 Survey

Survey Date: 2019

## Explorer Gender Breakdown

```{r gender}
explorer_gender
```

## School Data
```{r school, warning = FALSE}

# arrange the plots
(grades + gpa) / (lunch + absences + extracurriculars)
```

## Home Life
```{r home, warning=FALSE} 


(residents + siblings) / (siblings_over_twenty + languages)

```

## Household Education

```{r household_edu, warning=FALSE}

siblings_college + father_edu_plot + mother_edu_plot

```

## Post High School

```{r post_high, warning=FALSE}
post_high_school
```
